### ISSUE TITLE
SonarQube compatibility question

### ISSUE THREAD

**Issue by BlackSmokee** [edwinyangzh/sonar-java-i18n-checks#6]
Hi, @edwinyangzh! 

I have a question is this plugin compatible with Sonar 8.9 (LTS) and newer? 

Thank you!

**Comment by edwinyangzh** [comment]
Hi BlackSmokee,

A newer version of this plugin can be found here: https://github.com/vmware-samples/SonarQube-Plugin-for-Java, it is compatible with 8.9 (LTS) and newer.

**Comment by BlackSmokee** [comment]
Thank you, @edwinyangzh !
